

version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: jwgl6HTumxu6JEghfrflBugfiDLYm9a5
      POSTGRES_DB: projectdb_6erv
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - dslabdb:/var/lib/postgresql/data

  spring:
    build:
      context: .
      dockerfile: test.dockerfile
    image: sp
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/projectdb_6erv
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: jwgl6HTumxu6JEghfrflBugfiDLYm9a5
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"

volumes:
  dslabdb:
