pipeline {
  agent any

  environment {
    DOCKER_IMAGE = "gglaros/app"
    TAG = "latest"
    KUBECONFIG = credentials('/.kube/devops2') 
  }

  stages {
    stage('Checkout') {
      steps {
        git 'https://github.com/gglaros/devops'  // βάλτο το URL του νέου repo σου
      }
    }

    stage('Build App') {
      steps {
        sh 'mvn clean package -DskipTests'
      }
    }

    stage('Build Docker Image') {
      steps {
        sh "docker build -t $DOCKER_IMAGE:$TAG ."
      }
    }

    stage('Push to Docker Hub') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
          sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
          sh "docker push $DOCKER_IMAGE:$TAG"
        }
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        sh 'kubectl apply -f kubernetes/'
      }
    }
  }
}

