- name: Install docker-compose (v1 legacy)
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'


- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /home/{{ ansible_user }}/docker-compose.yml
    mode: '0644'

- name: Run docker-compose up
  shell: docker-compose up -d
  args:
    chdir: /home/{{ ansible_user }}

